#Feature: Authorization
#   In order to do ..........
#    I need the right privileges


#   Scenario: Admin can do.....
#    Given ......
#   Given I am authenicated as......
#    Given i am on the home page
#    Then I should ........